# Generated by Django 4.0 on 2021-12-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_email_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
