# Generated by Django 3.2.8 on 2021-11-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_skill', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('time_use', models.IntegerField()),
            ],
        ),
    ]
