# Generated by Django 4.0 on 2021-12-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalpage', '0004_auto_20211124_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySoftSkills',
        ),
    ]
