# Generated by Django 4.0 on 2021-12-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalpage', '0005_delete_mysoftskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskills',
            name='count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='myskills',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myskills',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
