# Generated by Django 4.0 on 2022-01-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalpage', '0006_myskills_count_alter_myskills_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(blank=True, max_length=100, verbose_name='Назва проекта')),
                ('description', models.TextField(blank=True, verbose_name='Опис проекта')),
                ('link_on_github', models.CharField(blank=True, max_length=100, verbose_name='Силка на GitHub проекта')),
            ],
            options={
                'verbose_name': 'Мої проекти',
                'verbose_name_plural': 'Мої проекти',
                'ordering': ['id', 'name_project'],
            },
        ),
    ]
